" alternate {
    " search path
    "   sfr: relative to the current file
    "   dwr: relative to current working directory
    "   abs: absolute path
    "   reg: regex path
    let g:alternateSearchPath = 'dwr:include,dwr:src'
            \ .'sfr:../include,sfr:../src'
            \ .'reg:/src/include/g/,reg:/include/src/g/'
" }
